apiVersion: v1
kind: Service
metadata:
  name: dfcu-demo
  namespace: namespace-workflow-1696858778890
spec:
  type: LoadBalancer
  selector:
    app: dfcu-demo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000